'use client';
import { useState } from 'react';
import { UsageGate } from '@/components/UsageGate';
import { ToolLayout } from '@/components/ToolLayout';
import { UploadZone } from '@/components/UploadZone';
import { Loader2, Image as ImageIcon } from 'lucide-react';

async function incrementUsage(toolName: string) {
  const fingerprint = sessionStorage.getItem('fp') || '';
  await fetch('/api/increment-usage', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ fingerprint, toolName }),
  });
}

export default function ReplaceBackgroundPage() {
  const [file, setFile] = useState<File | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string>('');
  const [resultUrl, setResultUrl] = useState<string>('');
  const [prompt, setPrompt] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [error, setError] = useState<string>('');

  const handleFile = (f: File) => {
    setFile(f);
    setPreviewUrl(URL.createObjectURL(f));
    setResultUrl('');
    setError('');
  };

  const handleProcess = async () => {
    if (!file || !prompt) return;
    setIsProcessing(true);
    setError('');
    try {
      const formData = new FormData();
      formData.append('image', file);
      formData.append('prompt', prompt);

      const response = await fetch('/api/replace-background', {
        method: 'POST',
        body: formData,
      });

      if (!response.ok) {
        throw new Error(await response.text());
      }

      const blob = await response.blob();
      setResultUrl(URL.createObjectURL(blob));
      await incrementUsage('replace-bg');
    } catch (e: any) {
      setError(e.message || 'Processing failed');
    } finally {
      setIsProcessing(false);
    }
  };

  const handleDownload = () => {
    const a = document.createElement('a');
    a.href = resultUrl;
    a.download = 'replaced-background.png';
    a.click();
  };

  const leftPanel = (
    <div className="space-y-4">
      <UploadZone onFile={handleFile} preview={previewUrl} label="Upload your image" />
      <div>
        <label htmlFor="prompt" className="text-sm font-semibold text-text-primary block mb-2">Prompt</label>
        <textarea
          id="prompt"
          name="Prompt"
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Describe the new background..."
          className="w-full h-24 rounded-lg bg-surface border border-border p-3 text-sm text-text-primary focus:border-accent focus:outline-none resize-none"
        />
      </div>
      {!isProcessing ? (
        <button
          onClick={handleProcess}
          disabled={!file || !prompt.trim()}
          className="btn-primary w-full flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Generate
        </button>
      ) : (
        <button disabled className="btn-primary w-full flex items-center justify-center gap-2 opacity-70">
          <Loader2 size={16} className="animate-spin" /> Processing...
        </button>
      )}
      {error && <p className="text-error text-sm">{error}</p>}
    </div>
  );

  const rightPanel = (
    <div className="card min-h-64 flex items-center justify-center" data-testid="result-zone">
      {isProcessing ? (
        <div className="text-center text-muted" data-testid="loading-indicator">
          <Loader2 size={48} className="animate-spin mx-auto mb-4 text-accent" />
          <p>Replacing background...</p>
        </div>
      ) : resultUrl ? (
        <img
          data-testid="result-image"
          src={resultUrl}
          alt="Result"
          className="rounded-xl max-h-96 max-w-full object-contain"
        />
      ) : (
        <div className="text-center text-muted">
          <ImageIcon size={48} className="mx-auto mb-4 opacity-30" />
          <p>Result will appear here</p>
        </div>
      )}
    </div>
  );

  return (
    <UsageGate toolName="replace-bg">
      <ToolLayout
        toolName="replace-bg"
        title="Replace Background"
        description="Remove your background and replace it with any scene generated by AI."
        leftPanel={leftPanel}
        rightPanel={rightPanel}
        resultUrl={resultUrl}
        onDownload={handleDownload}
      />
    </UsageGate>
  );
}
